article_list =[
    "Podokesaurus is a genus of coelophysoid dinosaur that lived in what is now the eastern United States during the Early Jurassic Period between 201 and 190 million years ago Its only fossil was discovered by the geologist Mignon Talbot near Mount Holyoke Massachusetts in 1910 Talbot described and named the new genus and species Podokesaurus holyokensis based on it becoming the first woman to find and describe a dinosaur The holotype fossil pictured was recognised as significant and was studied by other researchers but was lost when the building it was in burned down in",
    "This site is a part of the Wadden Sea on the North Sea coast north of the city of Bremerhaven in the Land of Hamburg Situated close to the mouth of the Elbe River it represents an estuary system which is the habitat for the seal Phoca vitulina and a large diversity of birds and fish The nutrient rich waters of the Elbe support a high biomass production and are important for fish spawning The site includes sand and mudflats with channels islands and saltmarshes The site has been designated as a National Park Ramsar site and EU Special Protection Area for wild birds",
    "His other works include Palimpsest performed as part of the QSO Maestro Series conducted by Muhai Tang; Sanctuary a double oboe and Cor Anglais concerto composed for Diana Doherty Alexandre Ougey and Camerata performed at the Queensland Music Festival; American Spirit composed for Black and Fantaskatto a vocal scat concerto composed for Olivia Chindamo both performed by the Queensland Symphony Orchestra",
    "The race was dominated by Alberto Ascari who led from pole and pulled away comfortably each lap The only slight drama came on the final tour: he had run the full distance without pitting and some spokes on his right rear wheel broke in the banked Karussell However such was his lead that he could afford to significantly reduce his pace nursing the car home to victory",
    "The final episode consists of Molly Bloom's thoughts as she lies in bed next to her husband The episode uses a stream-of-consciousness technique in eight paragraphs and lacks punctuation Molly thinks about Boylan and Bloom her past admirers including Lieutenant Stanley G Gardner the events of the day her childhood in Gibraltar and her curtailed singing career She also hints at a lesbian relationship in her youth with a childhood friend named Hester Stanhope These thoughts are occasionally interrupted by distractions such as a train whistle or the need to urinate Molly considers the proximity of her menstrual period following her extra-marital affairs with Boylan and believes the early return of her period is the reason for her increased sexual appetite",
]


# str ="The final episode consists of Molly Bloom's thoughts as she lies in bed next to her husband. The episode uses a stream-of-consciousness technique in eight paragraphs and lacks punctuation. Molly thinks about Boylan and Bloom, her past admirers, including Lieutenant Stanley G. Gardner, the events of the day, her childhood in Gibraltar, and her curtailed singing career. She also hints at a lesbian relationship, in her youth, with a childhood friend named Hester Stanhope. These thoughts are occasionally interrupted by distractions, such as a train whistle or the need to urinate. Molly considers the proximity of her menstrual period following her extra-marital affairs with Boylan, and believes the early return of her period is the reason for her increased sexual appetite."
# str = str.replace(",", "")
# str = str.replace(".", "")
# str = str.replace("(", "")
# str = str.replace(")", "")
# lst =str.split(" ")
# print(str)